apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sparrow-web
  name: sparrow-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparrow-web
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sparrow-web
    spec:
      containers:
        - image: sparrowprod.azurecr.io/sparrow-web-dev:_BUILD__ID_
          name: sparrow-web
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 1422

---
apiVersion: v1
kind: Service
metadata:
  name: sparrow-web
  labels:
    run: sparrow-web
spec:
  type: ClusterIP
  selector:
    app: sparrow-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1422