name: Deploy to App Center

on:
  push:
    branches:
      - development
env: 
 VITE_API_URL: ${{secrets.VITE_API_URL}}
 
jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Windows SDK
        run: Invoke-WebRequest -Uri https://aka.ms/winsdk/10/latest/SdkSetup.exe -OutFile $env:TEMP\SdkSetup.exe
        shell: powershell

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      # - name: Install App Center CLI
      #   run: |
      #     npm install -g appcenter-cli
      
      # - name: Log in to App Center
      #   run: |
      #     appcenter login --token ${{ secrets.APPCENTER_API_TOKEN }}
      
      # - name: Upload to App Center
      #   run: |
      #     appcenter distribute release -f ./sparrow-app/src-tauri/target/release/bundle/msi -g Collaborators -a testsp
      #   env:
      #     APPCENTER_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}

      - name: Install App Center CLI
        run: |
          npm install -g appcenter-cli

      # - name: Install Yarn
      #   run: |
      #     sudo apt-get update -q
      #     sudo apt-get install -y curl
      #     curl -o- -L https://yarnpkg.com/install.sh | bash
      #     export PATH=$HOME/.yarn/bin:$PATH
          
      - name: Install dependencies
        run: |
          yarn install
          yarn build
          yarn tauri build

      - name: sign msi
        run: |
           $cert = New-SelfSignedCertificate -Subject "CN=Certificate" -CertStoreLocation "Cert:\LocalMachine\My" -KeyUsage DigitalSignature -Type CodeSigningCert -KeySpec Signature -NotAfter (Get-Date).AddDays(90)
           $certPath = "Cert:\LocalMachine\My\$($cert.Thumbprint)"
           $password = ConvertTo-SecureString -String "sparrow123" -Force -AsPlainText
           Export-PfxCertificate -Cert $certPath -FilePath "D:\a\sparrow-app\sparrow-app\src-tauri\target\release\bundle\Certificate.pfx" -Password $password
           & "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x86\SignTool.exe" sign /f "D:\a\sparrow-app\sparrow-app\src-tauri\target\release\bundle\Certificate.pfx" /p sparrow123 /tr http://timestamp.digicert.com /td sha256 /fd sha256 /v "D:\a\sparrow-app\sparrow-app\src-tauri\target\release\bundle\msi\Sparrow-app_0.0.0_x64_en-US.msi"
           
      # - name: Install App Center CLI
      #   run: |
      #     npm install -g appcenter-cli
        
      - name: Upload to App Center
        run: |
          appcenter login --token ${{ secrets.APPCENTER_API_TOKEN }}
          appcenter distribute release -f D:\a\sparrow-app\sparrow-app\src-tauri\target\release\bundle\msi\sparrow-app_0.0.0_x64_en-US.msi -g Collaborators --app Techdome/Sparrow --build-version v1.0.1
        # env:
        #   APPCENTER_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}

          
      #- name: Archive the MSI Folder
        #run: |
          # Archive the MSI folder (replace the path with the correct one)
          #tar -czvf app.tar.gz -C D:\a\sparrow-app\sparrow-app\src-tauri\target\release\bundle\msi .

      # - name: Deploy to App Center
      #   run: |
      #     # Upload the archive to App Center (replace with your App Center app name)
      #     appcenter distribute release -f app.tar.gz -g Collaborators -a Sparrow 
      #     appcenter login --token ${{ secrets.APPCENTER_API_TOKEN }}

      #   env:
      #     APPCENTER_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}
       
      # - name: Upload to App Center
      #   uses: wzieba/AppCenter-Github-Action@v1
      #   with:
      #     appName: wzieba/Sample-App
      #     token: ${{secrets.APPCENTER_API_TOKEN}}
      #     group: Collaborators
      #     file: ./sparrow-app/src-tauri/target/release/bundle/msi .
      #     notifyTesters: true
      #     debug: false
        # uses: andymckay/action-appcenter-upload@v3
        # with:
        #   app_secret: ${{ secrets.APPCENTER_API_TOKEN }}
        #   owner_name: anjali.malviya-techdome.net.in
        #   app_name: Sparrow-1
        #   group: Collaborators
        #   file: app.tar.gz
